---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: external-adapter-pvc-{{ version_name }}
  namespace: {{ namespace }}
spec:
  storageClassName: {{ storage_class_name }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

