---
kind: Service
apiVersion: v1
metadata:
  name: external-adapter-svc-node
  namespace: {{ namespace }}
  labels:
    component: external-adapter
spec:
  ports:
    - name: external-adapter
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: {{ node_port }}
  selector:
    component: external-adapter
  type: NodePort

---
kind: Service
apiVersion: v1
metadata:
  name: external-adapter-svc
  namespace: {{ namespace }} 
  labels:
    component: external-adapter
spec:
  ports:
  - name: external-adapter-port
    protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    component: external-adapter
  type: ClusterIP  
  
---
kind: Service
apiVersion: v1
metadata:
  name: external-adapter-svc-headless
  namespace: {{ namespace }}
  labels:
    component: external-adapter
spec:
  ports:
    - name: external-adapter-port
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    component: external-adapter
  clusterIP: None

