---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-adapter
  namespace: fraxses-sandbox-env
spec:
  replicas: 1
  selector:
    matchLabels:
      component: external-adapter
  template:
    metadata:
      labels:
        component: external-adapter
    spec:
      terminationGracePeriodSeconds: 10
      imagePullSecrets:
        - name: fraxses-reg-cred
      containers:
        - name: external-adapter-img
          imagePullPolicy: Always
          image: austpryb/external-adapter:001
          env:
            - name: SMTP_USERNAME
              value: app.clutch.health
            - name: SMTP_PASSWORD            
              value: hsjpvvjxadqfmyhh
            - name: FRAXSES_API_GATEWAY
              value: https://sandbox.fraxses.com/api/gateway
            - name: FRAXSES_USERNAME
              value: admin
            - name: FRAXSES_PASSWORD
              value: admin
          ports:
            - containerPort: 8080
              name: external-adapter-port
          terminationMessagePath: "/dev/termination-log"
          terminationMessagePolicy: File
          resources:
            requests:
              memory: 1000Mi
              cpu:  1500m

