---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: external-adapter-pvc
  namespace: default
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

